### ISSUE TITLE
FIX: No participant, no data table

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#10]
## Value Statement
As a **user**
**I want** the participants table to be hidden when there are no participants yet.

## Description
![image](https://github.com/jecaps/kris-kringle/assets/76426580/cb6d312f-65c2-4b75-9462-38f63a655d08)

## Tasks
- [x] hide data table when there are no participants yet

## Size
small

**Comment by akanz1** [comment]
Can you center it? 

![image](https://github.com/jecaps/kris-kringle/assets/51492342/f8676900-4ebc-4233-b540-816e736a646c)

**Comment by jecaps** [comment]
> Can you center the buttons for join group and share link?

I'll update asap

**Comment by akanz1** [comment]
![image](https://github.com/jecaps/kris-kringle/assets/51492342/c518a77f-3b94-4e61-8e6e-475e49553a0b)
