### ISSUE TITLE
FIX: Password-match checking

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#11]
## Value Statement
Password-match checking happens only when the create button is clicked.

## Description
![image](https://github.com/jecaps/kris-kringle/assets/76426580/97753d12-90d3-4db3-9cb4-58f69b73b200)

## Tasks
- [x] implement password-match checking while password is being encoded
- [x] apply styling when passwords do not match

## Size
small

**Comment by akanz1** [comment]
Works! 

![image](https://github.com/jecaps/kris-kringle/assets/51492342/29d0bc3a-ca09-42ad-b1b5-7ab87ef7c115)
