### ISSUE TITLE
FIX: Button text position

### ISSUE THREAD

**Issue by jecaps** [jecaps/kris-kringle#12]
## Value Statement
Text inside the close button after adding a member is not in the center.

## Description
![image](https://github.com/jecaps/kris-kringle/assets/76426580/4040d602-7f67-4a80-876f-4cea431b6f6e)

## Tasks
- [ ] Position button text in the center

## Size
small

**Comment by akanz1** [comment]
Good job! 
![image](https://github.com/jecaps/kris-kringle/assets/51492342/ec617651-1f65-40ce-844c-7439dd503b88)
